edgar.audit.dashboard:
    path: /audit/dashboard
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditDashboard:dashboard'

edgar.audit.configure:
    path: /audit/configure
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditConfigure:configure'

edgar.audit.export:
    path: /audit/export
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditExport:export'

edgar.audit.export.ask:
    path: /audit/export/ask
    methods: ['POST']
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditExport:askExport'

edgar.audit.export.download:
    path: /audit/export/download/{exportId}/{filename}
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditExport:download'
    requirements:
        exportId: \d+

edgar.audit.delete.log:
    path: /audit/delete-log/{id}
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditExport:deleteLog'

edgar.audit.export.now:
    path: /audit/export/now
    defaults:
        _controller: 'EdgarEzUIAuditBundle:AuditExport:exportNow'