imports:
    - { resource: controllers.yml }
    - { resource: audits.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIAudit\Handler\:
        resource: "../../../lib/Handler/*"
        public: true

    Edgar\EzUIAuditBundle\Cron\AuditExportCron:
        tags:
          - { name: "edgar.cron", alias: "audit_export", priority: 100, expression: "*/5 * * * *" }

    Edgar\EzUIAuditBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzUIAudit\Form\Type\AuditTypeChoiceType: ~
