services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIAuditBundle\Audit\URLAlias\CreateGlobalUrlAliasAudit:
        tags:
            - { name: ezpublish.api.slot, signal: URLAliasService\CreateGlobalUrlAliasSignal }

    Edgar\EzUIAuditBundle\Audit\URLAlias\CreateUrlAliasAudit:
        tags:
            - { name: ezpublish.api.slot, signal: URLAliasService\CreateUrlAliasSignal }

    Edgar\EzUIAuditBundle\Audit\URLAlias\RemoveAliasesAudit:
        tags:
            - { name: ezpublish.api.slot, signal: URLAliasService\RemoveAliasesSignal }
